version: '2'
services:
  warden:
    build:
      context: .
      dockerfile: dockerfiles/warden/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./tmp/redis/:/testing-github-warden/tmp/redis/
    depends_on:
      - redis
    restart: always
    environment:
      - SECRET_TOKEN

  executioner:
    build:
      context: .
      dockerfile: dockerfiles/executioner/Dockerfile
    tty: true
    volumes:
      - ./tmp/redis/:/testing-github-warden/tmp/redis/
    command: ruby executioner.rb
    depends_on:
      - redis
    restart: always
    environment:
      - BUGZILLA_API_KEY
  redis:
    image: redis
    volumes:
      - ./tmp/redis:/data
    command: redis-server /data/redis.conf
    restart: always

volumes:
  redis_data:
