-
  :repository_name_array: ['test']
  :branch_pattern: 'test_branch_first|test_branch_other'
-
  :repository_name_array: ['sdkjs', 'server','core', 'web-apps-pro', 'web-apps',
                           'desktop-apps', 'desktop-apps-ext', 'desktop-sdk', 'core-ext',
                           'mobile-apps', 'web-apps-mobile', 'sdkjs-pivot-tables', 'sdkjs-sheet-views',
                           'documents-app-ios', 'editors-ios', 'documents-android',
                           'documents-app-android', 'document-android-editors']

  :branch_pattern: 'develop|hotfix|release'
-
  :repository_name_array: ['portals', 'ControlPanel', 'ControlPanel_Private']
  :branch_pattern: 'master|hotfix|release'
