-
  :repository_name_array: ['test']
  :branch_pattern: 'test_branch_first|test_branch_other'
-
  :repository_name_array: ['api.onlyoffice.com',
                           'build_tools',
                           'core',
                           'core-ext',
                           'desktop-apps',
                           'desktop-apps-ext',
                           'desktop-sdk',
                           'DocSpace',
                           'DocSpace-server',
                           'DocSpace-client',
                           'document-android-editors',
                           'document-server-integration',
                           'documents-android',
                           'documents-app-android',
                           'documents-app-ios',
                           'editors-ios',
                           'mobile-apps',
                           'onlyoffice',
                           'projects-mobile',
                           'sdkjs',
                           'sdkjs-forms',
                           'sdkjs-native',
                           'sdkjs-pivot-tables',
                           'sdkjs-sheet-views',
                           'server',
                           'web-apps',
                           'web-apps-mobile',
                           'web-apps-pro']

  :branch_pattern: 'develop|hotfix|release'
-
  :repository_name_array: ['ControlPanel',
                           'ControlPanel_Private',
                           'onlyoffice.github.io',
                           'portals']
  :branch_pattern: 'master|hotfix|release'
# For AVS projects
-
  :repository_name_array: ['activex',
                           'app-main']
  :branch_pattern: 'develop'
