-
  :repository_name_array: ['test']
  :branch_pattern: 'test_branch_first|test_branch_other'
-
  :repository_name_array: ['sdkjs', 'server','core', 'web-apps-pro', 'web-apps', 'desktop-apps', 'desktop-apps-ext', 'desktop-sdk', 'core-ext']
  :branch_pattern: 'develop|hotfix|release'
