-
  :repository_name_array: ['test']
  :branch_pattern: 'test_branch_first|test_branch_other'
-
  :repository_name_array: ['core',
                           'core-ext',
                           'desktop-apps',
                           'desktop-apps-ext',
                           'desktop-sdk',
                           'document-android-editors',
                           'documents-android',
                           'documents-app-android',
                           'documents-app-ios',
                           'editors-ios',
                           'mobile-apps',
                           'sdkjs',
                           'sdkjs-pivot-tables',
                           'sdkjs-sheet-views',
                           'server',
                           'web-apps',
                           'web-apps-mobile',
                           'web-apps-pro']

  :branch_pattern: 'develop|hotfix|release'
-
  :repository_name_array: ['portals', 'ControlPanel', 'ControlPanel_Private']
  :branch_pattern: 'master|hotfix|release'
