-
  :commit_message_pattern: '//'
  :action: 'nothing'
-
  :commit_message_pattern: 'test_commit_message'
  :action: 'test_action'
-
  :commit_message_pattern: '[F|f]ix(ed)? [B|b]ug #?\d+'
  :action: 'add_resolved_fixed'
-
  :commit_message_pattern: '[B|b]ug #?\d+'
  :action: 'add_comment'
