-
  :commit_message_pattern: '//'
  :action: 'nothing'
-
  :commit_message_pattern: 'test_commit_message'
  :action: 'test_action'
-
  :commit_message_pattern: 'fix(ed)?\s+bug\s+#?\d+'
  :action: 'add_resolved_fixed'
-
  :commit_message_pattern: 'bug\s+#?\d+'
  :action: 'add_comment'
