name: Check Configuration
on: [push]
jobs:
  check_configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up latest Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Run the script that checks for duplicates
        run: |
          ruby scripts/check_config_duplicates.rb
