name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BUGZILLA_API_KEY: ${{ secrets.BUGZILLA_API_KEY }}
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install bundler dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check source files using `rubocop`
        run: rubocop
      - name: run unit tests
        run: bundle exec rspec spec/unit --fail-fast
      - name: Start services in docker-compose
        run: docker-compose up -d
      - name: run integration tests
        run: bundle exec rspec spec/integration --fail-fast