name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BUGZILLA_API_KEY: ${{ secrets.BUGZILLA_API_KEY }}
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Check markdown files using `markdownlint`
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Start services in docker-compose
        run: docker-compose up -d
      - name: Install bundler dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Check source files using `rubocop`
        run: rubocop
      - name: run tests
        run: bundle exec rspec spec/tests --fail-fast
